### ISSUE TITLE
Establecer horarios de reuniones

### ISSUE THREAD

**Issue by AlejaDeV** [FADEDevs/HogarColombia#1]

**Comment by JhoanLozano** [comment]
Horarios:

Lunes - Media hora después de la clase (10:30 am)
Miercoles - Media hora después de la clase (10:30 am)
Viernes - (Tutoría a las 8 am)

https://docs.google.com/spreadsheets/d/1U-qPva-qyqLobqjbxPOqbvzX0chv5i1ZD84PBBV_1S0/edit#gid=0
